backend:
  name: github
  repo: bikisagar/AURELIA_TRADISIA_TEST   # e.g. jyotirmoy/aurelia-tradisia
  branch: main

# OAuth application callback URL (must match GitHub OAuth app setup)
base_url: https://aureliatradisia.in

media_folder: "images/uploads"    # Folder in repo where uploaded files are stored
public_folder: "/images/uploads"  # Public URL path for uploaded media

site_url: "https://aureliatradisia.in
logo_url: "/images/logo.svg"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "about.html"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "services.html"
        label: "Services Page"
        name: "services"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "portfolio.html"
        label: "Portfolio Page"
        name: "portfolio"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "contact.html"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
