backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "radiant-pothos-ed52f9.netlify.app"
logo_url: "/images/logo.svg"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Hero Heading, name: hero_heading, widget: string }
          - { label: Hero Description, name: hero_desc, widget: text }
      - file: "about.html"
        label: "About"
        name: "about"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
      - file: "services.html"
        label: "Services"
        name: "services"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    extension: "json"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Location, name: location, widget: string, required: false }
      - { label: Materials, name: materials, widget: list, required: false }
      - { label: Description, name: description, widget: text }
      - { label: Images, name: images, widget: list, fields: [ {label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string} ] }
